import type { BudgetReport, HealthReport, Severity } from "../core/types.js";

const SEV_LABEL: Record<Severity, string> = {
  error: "error",
  warn: "warn",
  info: "info",
};

/** Escape characters that would break a Markdown table cell. */
function esc(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function healthSection(report: HealthReport): string {
  if (report.noContext) {
    return [
      "## Context health — N/A",
      "",
      "No agent context files found (CLAUDE.md / AGENTS.md / .cursorrules / SKILL.md …) — nothing to audit. A repo with no context is not graded.",
    ].join("\n");
  }
  const lines: string[] = [];
  lines.push(`## Context health — ${report.grade} (${report.score}/100)`);
  lines.push("");
  lines.push(`Scanned ${report.files.length} context file(s).`);
  lines.push("");
  if (report.findings.length === 0) {
    lines.push("No issues found. ✅");
    return lines.join("\n");
  }
  lines.push("| Severity | Code | Location | Message |");
  lines.push("| --- | --- | --- | --- |");
  for (const f of report.findings) {
    const loc = f.line ? `${f.file}:${f.line}` : f.file ?? "";
    lines.push(`| ${SEV_LABEL[f.severity]} | \`${esc(f.code)}\` | ${esc(loc)} | ${esc(f.message)} |`);
  }

  // Actionable fixes, deduped, in first-seen order.
  const suggestions = [...new Set(report.findings.map((f) => f.suggestion).filter((s): s is string => !!s))];
  if (suggestions.length > 0) {
    lines.push("");
    lines.push("**Suggested fixes:**");
    lines.push("");
    for (const s of suggestions) lines.push(`- ${esc(s)}`);
  }
  return lines.join("\n");
}

function budgetSection(report: BudgetReport): string {
  const num = (n: number) => n.toLocaleString("en-US");
  const lines: string[] = [];
  lines.push(`## Token budget`);
  lines.push("");
  lines.push(`- **Always-on:** ${num(report.alwaysOnTokens)} tokens / turn — root context files + MCP schemas, loaded every turn.`);
  lines.push(`- **On-demand:** ${num(report.onDemandTokens)} tokens across ${report.onDemandCount} file(s) — skills / rules, loaded only when invoked.`);
  lines.push("");
  lines.push("| Source | Tokens | Load | Note |");
  lines.push("| --- | ---: | --- | --- |");
  for (const e of report.entries) {
    const load = e.load === "always" ? "always-on" : "on-demand";
    lines.push(`| ${esc(e.label)} | ${num(e.tokens)} | ${load} | ${e.note ? esc(e.note) : ""} |`);
  }
  lines.push("");
  const winPct = ((report.alwaysOnTokens / report.contextWindow) * 100).toFixed(1);
  lines.push(`→ always-on is ${winPct}% of a ${num(report.contextWindow)}-token window (every turn)`);
  if (report.estCostUsd != null) {
    lines.push("");
    lines.push(`→ est. ~$${report.estCostUsd.toFixed(4)} always-on input cost per turn`);
  }
  return lines.join("\n");
}

/** Render a PR-pasteable Markdown report from whichever reports were run. */
export function renderMarkdown(reports: { health?: HealthReport; budget?: BudgetReport }): string {
  const parts: string[] = ["# ctxweight report", ""];
  if (reports.health) parts.push(healthSection(reports.health), "");
  if (reports.budget) parts.push(budgetSection(reports.budget), "");
  parts.push("---", "");
  parts.push("_Generated by [ctxweight](https://github.com/GonzaloPeriane/ctxweight) — offline AI-context auditor._");
  return parts.join("\n") + "\n";
}
